name: Deploy Frontend Ke EC2
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Menjalankan eksekusi SSH ke Server EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "1. Narik kode frontend terbaru..."
            cd /home/ubuntu/syair/syair-fe
            git pull origin main

            echo "2. Re-build dan Restart khusus layanan frontend..."
            cd /home/ubuntu/syair

            docker compose up -d --build frontend
